version: '3.1'
services:
    db_vector:
        image: qdrant/qdrant
        ports:
          - 6333:6333
        volumes:
          - /d/data/qdrant_storage:/qdrant/storage
        networks:
          - llm-docker

    api_llm:
      build:
        context: .
        dockerfile: ./Dockerfile
      image: llm_api
      container_name: llm_api
      env_file: .env
      expose:
        - 8080
        - 3000
      restart: always
      tty: true
      depends_on:
        - db_vector
      networks:
        - llm-docker

    nginx_proxy:
      build:
        context: .
        dockerfile: ./Dockerfile.proxy
      image: nginx_proxy
      container_name: nginx_proxy
      env_file: .env
      ports:
        - 8080:8080
        - 80:80
      restart: always
      tty: true
      depends_on:
        - api_llm
        - db_vector
      networks:
        - llm-docker
        - api_gateway
      

   
networks:
  llm-docker:
    internal: true
  api_gateway:
  
